#!/bin/sh
#
# @name 3DR Iris test with multiple sensors
#
# @type Quadrotor Wide
#

sh /etc/init.d-posix/10016_iris

if [ $AUTOCNF = yes ]
then
	# EKF2
	param set EKF2_AID_MASK 2
	param set EKF2_EVP_NOISE 0.05
	param set EKF2_EVA_NOISE 0.05

	# LPE: Flow-only mode
	param set LPE_FUSION 242
	param set LPE_FAKE_ORIGIN 1

	param set MPC_ALT_MODE 2

    # enable fusion of landing target velocity
    param set LTEST_MODE 1
    param set PLD_HACC_RAD 0.1
fi

# Start up Landing Target Estimator module
landing_target_estimator start
